#!/usr/bin/env python
import discord, request
from discord.ext import commands
from datetime import datetime

#! ==
#! Bot frontend
#// install "Better Comments" extension to have color coded commments
#// for clearer code understanding.
#! ==

client = commands.Bot(command_prefix = r'/')
client.remove_command("help")

#! ADD DETAILS HERE
bot_token = ""
welcome_channel_id = ""

#! ==

#?     _       _ _   _       _ _         
#?   (_)_ __ (_) |_(_) __ _| (_)_______ 
#?   | | '_ \| | __| |/ _` | | |_  / _ \
#?   | | | | | | |_| | (_| | | |/ /  __/
#?   |_|_| |_|_|\__|_|\__,_|_|_/___\___|
#?
#* These functions will trigger automatically.

#! PRINT MESSAGE ON ACTIVATION
@client.event
async def on_ready():
    await client.change_presence(activity=discord.Game('with humans'))
    print("hola humans ;)")


#! GREET NEW USERS
@client.event
async def on_member_join(member):
    embed=discord.Embed(title="°✧ :ribbon: **WЄLCOMЄ** :ribbon: ✧°", description="︶︶︶︶︶︶︶︶︶︶︶︶˚", color=request.random_color())
    embed.set_author(name="ivis-bot", url="https://github.com/LexxFade/Ivis-Bot", icon_url="https://i.ibb.co/4FsyjQR/ivis.png")    
    embed.set_thumbnail(url= member.avatar_url)
    embed.add_field(name="°", value=f"Greetings {member}!\nCheck out #rules and #roles to get started.\n**✧**", inline=False)
    embed.set_footer(text=f"Total members: {len(list(member.guild.members))}", icon_url=member.guild.icon_url)
    farm = client.get_channel(id=welcome_channel_id)
    await farm.send(embed=embed)

#! COVID STATUS
@client.command(aliases=['covid', 'corona'])
async def covidstats(ctx, country, state="All"):
    stats = request.covid(country, state)
    if stats == 0:
        await ctx.send("Location not found :/")
    else:
        embed=discord.Embed(title="°✧ :alembic: **Covid Stats** :microbe: ✧°", description=r"︶︶︶︶︶︶︶︶︶︶︶︶˚", color=request.random_color())
        embed.set_author(name="ivis-bot", url="https://github.com/LexxFade/Ivis-Bot", icon_url="https://i.ibb.co/4FsyjQR/ivis.png")
        embed.set_thumbnail(url="https://www.distancecme.com/wp-content/uploads/2020/03/coronavirus_round.png")
        embed.add_field(name="Confirmed Cases", value=stats[0], inline=False)
        embed.add_field(name="Recovered", value=stats[1], inline=False)
        embed.add_field(name="Died", value=stats[2])
        embed.set_footer(text='GitHub.com/LexxFade/Ivis-Bot')
        await ctx.send(embed=embed)    

#! ==

#?                                                  _     
#?     ___ ___  _ __ ___  _ __ ___   __ _ _ __   __| |___ 
#?    / __/ _ \| '_ ` _ \| '_ ` _ \ / _` | '_ \ / _` / __|
#?   | (_| (_) | | | | | | | | | | | (_| | | | | (_| \__ \
#?    \___\___/|_| |_| |_|_| |_| |_|\__,_|_| |_|\__,_|___/
#?   
#* Commands which will be triggered by the user 

#! YOUTUBE COMMAND
@commands.guild_only()
@client.command(aliases=['youtube', 'YOUTUBE'])
async def yt(ctx, *, query):
    await ctx.send(f"https://youtube.com/watch?v={request.youtube(query)}")


#! ARCH USER REPOSITORY
@commands.guild_only()
@client.command(aliases=['arch', 'AUR', 'git-clone'])
async def aur(ctx, *, query):
    aur_result = request.aur(query)
    embed=discord.Embed(title=f"{query}", url=f"https://aur.archlinux.org/packages/?O=0&SeB=n&K={aur_result[0]}&outdated=&SB=p&SO=d&PP=50&do_Search=Go", color=request.random_color())
    embed.set_author(name="ivis-bot", url="https://github.com/LexxFade/Ivis-Bot", icon_url="https://i.ibb.co/4FsyjQR/ivis.png")
    embed.set_thumbnail(url="https://ilug-cal.org/wp-content/uploads/2018/10/arch-linux.png")
    if aur_result[1] == 0:
        embed.add_field(name="No result found", value=f"no package with the name {query} found :/", inline=False)
    else:
        for i in range(1, len(aur_result)):
            package_title = request.char_manage(aur_result[i][0], ' ')
            embed.add_field(name=f"{package_title} [{aur_result[i][1]}]", value=f"{aur_result[i][2]}\n``https://aur.archlinux.org/{aur_result[i][0]}.git``", inline=False)

    embed.set_footer(text="type /help for more info")
    await ctx.send(embed=embed)


#! PING
@commands.guild_only()
@client.command()
async def ping(ctx):
    await ctx.send(f"📡 {int(client.latency * 1000)}m/s")


#! HELP
@commands.guild_only()
@client.command(aliases=['info', 'about', 'HELP'])
async def help(ctx):
    embed=discord.Embed(title="°✧ :ribbon: **HЄLPÐЄSK** :ribbon: ✧°", description=r"︶︶︶︶︶︶︶︶︶︶︶︶˚", color=request.random_color())
    embed.set_author(name="ivis-bot", url="https://github.com/LexxFade/Ivis-Bot", icon_url="https://i.ibb.co/4FsyjQR/ivis.png")
    embed.set_thumbnail(url="https://i.ibb.co/4FsyjQR/ivis.png")
    embed.add_field(name="𝔸𝕓𝕠𝕦𝕥", value=request.about, inline=False)
    embed.add_field(name="ℂ𝕠𝕟𝕗𝕖𝕤𝕤𝕚𝕠𝕟", value=request.confessions, inline=False)
    embed.add_field(name="ℂ𝕠𝕞𝕞𝕒𝕟𝕕𝕤", value=request.commands)
    embed.set_footer(text='GitHub.com/LexxFade/Ivis-Bot')
    await ctx.send(embed=embed)


#! SET CONFESSION CHANNEL
@commands.guild_only()
@client.command(aliases=['confessinit', 'setconfess'])
async def confesschannel(ctx, given_id):
    file = open("./server_data/confession_channel.txt", "w")
    file.write(given_id[2:-1])
    file.close()
    await ctx.send(f"{given_id} has been set as the confession channel.")


#! CONFESSION COMMAND
@client.command(aliases=['listen', 'confession'])
async def confess(ctx, *, confession):
    if isinstance(ctx.channel, discord.channel.DMChannel):
        try:
            file = open("./server_data/confession_channel.txt", "r")
            channel_id = int(file.read())
            file.close()
            if (len(confession) > 15):
                channel = client.get_channel(channel_id)
                time_now = datetime.now()
                unique_id = request.random_id()
                time_syntaxed = time_now.strftime("%d/%m %H:%M")
                embed = discord.Embed(title=r"°✧ :ribbon: **CONFESSION** :ribbon: ✧°", description = confession, color=request.random_color())
                embed.set_thumbnail(url="https://i.ibb.co/wCY1tvQ/confess.png")
                embed.set_author(name=f"id: {unique_id}")
                embed.set_footer(text=time_syntaxed)
                await channel.send(embed=embed)
                embed.description = f"Your confession has been posted at <#{channel_id}> anonymously ;)"
                await ctx.send(embed=embed)
            else:
                await ctx.send("C'mon fam no confession is that small :/")
        except:
            await ctx.send("Ask staff to initialize a confesstion channel by typing `/setconfess {ping channel}`")
    else:
        await ctx.send("its better to confess in DMs :)")

#! ==

#?    ___ _ __ _ __ ___  _ __ ___ 
#?   / _ \ '__| '__/ _ \| '__/ __|
#?  |  __/ |  | | | (_) | |  \__ \
#?   \___|_|  |_|  \___/|_|  |___/
#?                                
#* instead of giving error messages on invalid syntax, bot will show commmand info

#! YT CMD INFO
@yt.error
async def youtube_error(ctx, error):
    if isinstance(error, commands.MissingRequiredArgument):
        embed=discord.Embed(title="YouTube", url="https://www.youtube.com", color=0xff0000)
        embed.set_author(name="ivis-bot", url="https://github.com/LexxFade/Ivis-Bot", icon_url="https://i.ibb.co/4FsyjQR/ivis.png")
        embed.set_thumbnail(url="https://img.talkandroid.com/uploads/2014/06/YouTube_App_Large_Icon-450x450.png")
        embed.add_field(name="About", value="Search youtube videos right here from discord!", inline=False)
        embed.add_field(name="Commands", value="`/yt {query}` | `/youtube {query}` | `/vid {query}`", inline=False)
        embed.set_footer(text="type /help for more info")
        await ctx.send(embed=embed)


#! AUR CMD INFO
@aur.error
async def aur_error(ctx, error):
    if isinstance(error, commands.MissingRequiredArgument):
        embed=discord.Embed(title="Arch User Repository", url="https://aur.archlinux.org/", color=0x1791cf)
        embed.set_author(name="ivis-bot", url="https://github.com/LexxFade/Ivis-Bot", icon_url="https://i.ibb.co/4FsyjQR/ivis.png")
        embed.set_thumbnail(url="https://ilug-cal.org/wp-content/uploads/2018/10/arch-linux.png")
        embed.add_field(name="About", value="Search for AUR packages, and their `git-clone`, right here from discord!", inline=False)
        embed.add_field(name="Commands", value="`aur {package name}` | `arch {package name}` |\n `git-clone {package name}`", inline=False)
        embed.set_footer(text="type /help for more info")
        await ctx.send(embed=embed)


#! ABOUT ADDING/MODIFYING CONFESSION CHANNEL
@confesschannel.error
async def confesschannel_error(ctx, error):
    if isinstance(error, commands.MissingRequiredArgument):
        await ctx.send("type `/confesschannel {channel-id}` without `{}`\n**Note:** Enter `channel-id` and not just ping the channel-`#channel`")


#! CONFESSION INFO
@confess.error
async def confess_error(ctx, error):
    if isinstance(error, commands.MissingRequiredArgument):
        embed=discord.Embed(title="Confession", color=request.random_color())
        embed.set_author(name="ivis-bot", url="https://github.com/LexxFade/Ivis-Bot", icon_url="https://i.ibb.co/4FsyjQR/ivis.png")
        embed.set_thumbnail(url="https://cdn.pixabay.com/photo/2013/07/13/12/47/girl-160326__340.png")
        embed.add_field(name="About", value="DM me your confession and I will post it in the confession channel anonymously ;)", inline=False)
        embed.add_field(name="DM Syntax", value="`/listen {message}` | `/confess {message}` | `/confession {message}`", inline=False)
        embed.set_footer(text="type /help for more info")
        await ctx.send(embed=embed)


#! COVID STATS FOR DEFAULT PLACE WOULD BE SHOWED IF NO COUNTRY NAME IS PROVIDED
@covidstats.error
async def covidstats_error(ctx, error):
    #! add default country and state here
    stats = request.covid("default_country", "default_state")
    embed=discord.Embed(title="°✧ :alembic: **Covid Stats** :microbe: ✧°", description=r"︶︶︶︶︶︶︶︶︶︶︶︶˚", color=request.random_color())
    embed.set_author(name="ivis-bot", url="https://github.com/LexxFade/Ivis-Bot", icon_url="https://i.ibb.co/4FsyjQR/ivis.png")
    embed.set_thumbnail(url="https://www.distancecme.com/wp-content/uploads/2020/03/coronavirus_round.png")
    embed.add_field(name="Confirmed Cases", value=stats[0], inline=False)
    embed.add_field(name="Recovered", value=stats[1], inline=False)
    embed.add_field(name="Died", value=stats[2])
    embed.set_footer(text='GitHub.com/LexxFade/Ivis-Bot')
    await ctx.send(embed=embed)


#! INVALID COMMAND- SHOW MESSAGE HOW TO GET INVOLVED IN DEVELOPMENT AKA SHARE SUGGESTIONS
@client.event
async def on_command_error(ctx, error):
    if isinstance(error, commands.CommandNotFound):
        embed=discord.Embed(title="Command Not Found", description="The command you're trying does not exists....yet.\nAdd issues/PR on my GitHub if you have more suggestions", color=request.random_color())
        embed.set_author(name="ivis-bot", url="https://github.com/LexxFade/Ivis-Bot", icon_url="https://i.ibb.co/4FsyjQR/ivis.png")
        embed.set_thumbnail(url="https://i.pinimg.com/originals/6c/da/e5/6cdae5ec608d8df875c5766a5c24bf3e.png")
        embed.set_footer(text="type /help for bot-commands")
        await ctx.send(embed=embed)

#! ==

client.run(bot_token)
