#!/usr/bin/env python
import discord, request
from discord.ext import commands
from datetime import datetime

client = commands.Bot(command_prefix = r'/')
client.remove_command("help")

@client.event
async def on_ready():
    await client.change_presence(activity=discord.Game('with humans'))
    print("hola humans ;)")

@commands.guild_only()
@client.command(aliases=['youtube', 'YOUTUBE'])
async def yt(ctx, *, query):
    await ctx.send(f"https://{request.youtube(query)}")

@youtube.error
async def youtube_error(ctx, error):
    if isinstance(error, commands.MissingRequiredArgument):
        embed=discord.Embed(title="YouTube", url="https://www.youtube.com", color=0xff0000)
        embed.set_author(name="ivis-bot", url="https://github.com/LexxFade/Ivis-Bot", icon_url="https://i.ibb.co/4FsyjQR/ivis.png")
        embed.set_thumbnail(url="https://img.talkandroid.com/uploads/2014/06/YouTube_App_Large_Icon-450x450.png")
        embed.add_field(name="About", value="Search youtube videos right here from discord!", inline=False)
        embed.add_field(name="Commands", value="`/yt {query}` | `/youtube {query}` | `/vid {query}`", inline=False)
        embed.set_footer(text="type /help for more info")
        await ctx.send(embed=embed)

@commands.guild_only()
@client.command(aliases=['arch', 'AUR', 'git-clone'])
async def aur(ctx, *, query):
    aur_result = request.aur(query)
    embed=discord.Embed(title=f"more results of {query}", url=f"https://aur.archlinux.org/packages/?O=0&SeB=n&K={aur_result[0]}&outdated=&SB=p&SO=d&PP=50&do_Search=Go", color=request.random_color())
    embed.set_author(name="ivis-bot", url="https://github.com/LexxFade/Ivis-Bot", icon_url="https://i.ibb.co/4FsyjQR/ivis.png")
    embed.set_thumbnail(url="https://ilug-cal.org/wp-content/uploads/2018/10/arch-linux.png")
    for i in range(1, 6):
        embed.add_field(name="aur_result[i][0]", value="aur_result[i][1]", inline=False)

    embed.set_footer(text="type /help for more info")
    await ctx.send(embed=embed)

@aur.error
async def aur_error(ctx, error):
    if isinstance(error, commands.MissingRequiredArgument):
        embed=discord.Embed(title="Arch User Repository", url="https://aur.archlinux.org/", color=0x1791cf)
        embed.set_author(name="ivis-bot", url="https://github.com/LexxFade/Ivis-Bot", icon_url="https://i.ibb.co/4FsyjQR/ivis.png")
        embed.set_thumbnail(url="https://ilug-cal.org/wp-content/uploads/2018/10/arch-linux.png")
        embed.add_field(name="About", value="Search for AUR packages, and their `git-clone`, right here from discord!", inline=False)
        embed.add_field(name="Commands", value="`aur {package name}` | `arch {package name}` |\n `git-clone {package name}`", inline=False)
        embed.set_footer(text="type /help for more info")
        await ctx.send(embed=embed)

@commands.guild_only()
@client.command()
async def ping(ctx):
    await ctx.send(f"📡 {int(client.latency * 1000)}m/s")

@commands.guild_only()
@client.command(aliases=['motivate'])
async def motivation(ctx):
    await ctx.send(f'https://tenor.com/view/{request.motivation()}')

@commands.guild_only()
@client.command(aliases=['info', 'about', 'HELP'])
async def help(ctx):
    embed=discord.Embed(title="°✧ :ribbon: **HЄLPÐЄSK** :ribbon: ✧°", description=r"︶︶︶︶︶︶︶︶︶︶︶︶˚", color=request.random_color())
    embed.set_author(name="ivis-bot", url="https://github.com/LexxFade/Ivis-Bot", icon_url="https://i.ibb.co/4FsyjQR/ivis.png")
    embed.set_thumbnail(url="https://i.ibb.co/4FsyjQR/ivis.png")
    embed.add_field(name="𝔸𝕓𝕠𝕦𝕥", value=request.about, inline=False)
    embed.add_field(name="ℂ𝕠𝕟𝕗𝕖𝕤𝕤𝕚𝕠𝕟", value=request.confessions, inline=False)
    embed.add_field(name="ℂ𝕠𝕞𝕞𝕒𝕟𝕕𝕤", value=request.commands))
    embed.set_footer(text='GitHub.com/LexxFade/Ivis-Bot')
    await ctx.send(embed=embed)

@commands.guild_only()
@client.command(aliases=['confessinit', 'setconfess'])
async def confesschannel(ctx, given_id):
    channel_id = given_id
    #todo save this in a file
    await ctx.send(f"<#{channel_id}> has been set as the confession channel.")

@confesschannel.error
async def confesschannel_error(ctx, error):
    if isinstance(error, commands.MissingRequiredArgument):
        await ctx.send("type `/confesschannel {channel-id}` without `{}`\n**Note:** Enter `channel-id` and not just ping the channel-`#channel`")

@client.command(aliases=['listen', 'confession'])
async def confess(ctx, *, confession):
    channel_id = request.channel_id()
    if channel_id == None:
        await ctx.send("Confession Channel has not been configured by the server staff. Spam their ass off :smiling_imp:\njkjk :joy:")
    else:
        if (len(confession) > 15):
            channel = client.get_channel(channel_id)
            time_now = datetime.now()
            unique_id = request.random_id()
            time_syntaxed = time_now.strftime("%d/%m %H:%M")
            embed = discord.Embed(title=r"°✧ :ribbon: **CONFESSION** :ribbon: ✧°", description = confession, color=request.random_color())
            embed.set_thumbnail(url="https://i.pinimg.com/originals/a3/8f/60/a38f60f5ec45b027a0922a7884e8925f.png")
            embed.set_author(name=f"id: {unique_id}")
            embed.set_footer(text=time_syntaxed)
            await channel.send(embed=embed)
            await ctx.send(f"Your confession has been posted at <#{channel_id}> with id: {unique_id}")
        else:
            await ctx.send("C'mon fam no confession is that small :/")

@confess.error
async def confess_error(ctx, error):
    if isinstance(error, commands.MissingRequiredArgument):
        embed=discord.Embed(title="Confession", color=request.random_color())
        embed.set_author(name="ivis-bot", url="https://github.com/LexxFade/Ivis-Bot", icon_url="https://i.ibb.co/4FsyjQR/ivis.png")
        embed.set_thumbnail(url="https://cdn.pixabay.com/photo/2013/07/13/12/47/girl-160326__340.png")
        embed.add_field(name="About", value="DM me your confession and I will post it in the confession channel anonymously ;)", inline=False)
        embed.add_field(name="DM Syntax", value="`/listen {message}` | `/confess {message}` | `/confession {message}`", inline=False)
        embed.set_footer(text="type /help for more info")
        await ctx.send(embed=embed)

@client.event
async def on_command_error(ctx, error):
    if isinstance(error, commands.CommandNotFound):
        embed=discord.Embed(title="Command Not Found", description="The command you're trying does not exists....yet.\nAdd issues/PR on my GitHub if you have more suggestions", color=request.random_color())
        embed.set_author(name="ivis-bot", url="https://github.com/LexxFade/Ivis-Bot", icon_url="https://i.ibb.co/4FsyjQR/ivis.png")
        embed.set_thumbnail(url="https://i.pinimg.com/originals/6c/da/e5/6cdae5ec608d8df875c5766a5c24bf3e.png")
        embed.set_footer(text="type /help for bot-commands")
        await ctx.send(embed=embed)

client.run('bot-token')
