#!/usr/bin/env python
import discord
from discord.ext import commands

class Confession(commands.Cog):
    def __init__(self, client):
        self.client = client

def setup(client):
    client.add_cog(Confession(client))
