#!/usr/bin/env python
import discord
from discord.ext import commands

# TODO
# ping
# chicken cmd
# member status- studying / playing / procrastinating [reminder- are you still ....] <will basically set timer for an hour and will confirm until action changed>
# status chart - time percent spent on what

class General(commands.Cog):
    def __init__(self, client):
        self.client = client

    @commands.command()
    async def ping(self, ctx):
        await ctx.send(f"{self.client.latency * 1000}ms")

def setup(client):
    client.add_cog(General(client))
