#!/usr/bin/env python
import discord
from discord.ext import commands

# TODO
# covid count
# youtube search
# uni news
# important dates- controled by admin. <can also get ping on em aka reminder kinda thingy>

class Get_Info(commands.Cog):
    def __init__(self, client):
        self.client = client

def setup(client):
    client.add_cog(Get_Info(client))
